# This file is a template, and might need editing before it works on your project.
# Full project: https://gitlab.com/pages/plain-html

deploy_staging:
  stage: deploy
  script:
    - echo "Deploy to staging server"
    - mkdir .public
    - cp -r * .public
    - cp -frv dist/* /var/opt/staging/dragonraja-mobile && rm -r .public
  only:
  - master